--1(5)
SELECT * FROM v$pdbs;
--2
select * from v$instance;
--3
select * from dba_registry;

--PDB GEW
--6
CREATE TABLESPACE TS_GEW_PDB
DATAFILE 'C:\TABLESPACES\TS_GEW_PDB.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 20M
EXTENT MANAGEMENT LOCAL;

CREATE TEMPORARY TABLESPACE TS_GEW_PDB_TEMP
TEMPFILE 'C:\TABLESPACES\TS_PDM_GEW_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 30M
EXTENT MANAGEMENT LOCAL;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;  
CREATE ROLE RL_GEWCORE_PDB;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE,
      DROP ANY TABLE,
      DROP ANY VIEW,
      DROP ANY PROCEDURE TO RL_GEWCORE_PDB;

CREATE PROFILE PR_GEWCORE_PDB LIMIT
  PASSWORD_LIFE_TIME 180 --NUMBER OF PASSWORD'S DAYS ALIVE
  SESSIONS_PER_USER 3 -- NUMBER OF USER'S SESSIONS
  FAILED_LOGIN_ATTEMPTS 7 --NUMBER OF LOGGIN ATTEMPTS
  PASSWORD_LOCK_TIME 1 --NUMBER OF LOCKED DAYS AFTER FAILED LOGIN
  PASSWORD_REUSE_TIME 10 --AFTER THIS DAYS NUMBER YOU CAN REPEAT PASSWORD
  PASSWORD_GRACE_TIME DEFAULT --DAYS NUMBER OF WARNING ABOUT CHANGE PASSWORD
  CONNECT_TIME 180 --IN MINUTE
  IDLE_TIME 30 --IN MINUTE

CREATE USER U1_GEW_PDB IDENTIFIED BY Pa$$w0rd
  DEFAULT TABLESPACE TS_GEW_PDB QUOTA UNLIMITED ON TS_GEW_PDB
  TEMPORARY TABLESPACE TS_GEW_PDB_TEMP
  PROFILE PR_GEWCORE_PDB
  ACCOUNT UNLOCK;

GRANT RL_GEWCORE_PDB TO U1_GEW_PDB;

GRANT CREATE SESSION TO U1_GEW_PDB;
